// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/cfa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cfa">> = Specific
  const handler = {} as typeof import("../../app/cfa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/employee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee">> = Specific
  const handler = {} as typeof import("../../app/employee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executive">> = Specific
  const handler = {} as typeof import("../../app/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../app/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing">> = Specific
  const handler = {} as typeof import("../../app/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product">> = Specific
  const handler = {} as typeof import("../../app/product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/hr/supabase/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/hr/supabase/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/hr/supabase/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/inventory/supabase/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/inventory/supabase/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/inventory/supabase/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/marketing/supabase/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/marketing/supabase/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/marketing/supabase/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/product/supabase/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/product/supabase/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/product/supabase/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/shared/ollama/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/shared/ollama/chat">> = Specific
  const handler = {} as typeof import("../../app/api/backend/shared/ollama/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/shared/supabase/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/shared/supabase/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/shared/supabase/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/access/employees/[employeeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/access/employees/[employeeId]">> = Specific
  const handler = {} as typeof import("../../app/api/executive/access/employees/[employeeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/access/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/access/employees">> = Specific
  const handler = {} as typeof import("../../app/api/executive/access/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/access/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/access/roles/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/executive/access/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/access/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/access/roles">> = Specific
  const handler = {} as typeof import("../../app/api/executive/access/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/chat">> = Specific
  const handler = {} as typeof import("../../app/api/executive/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/history/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/history/messages">> = Specific
  const handler = {} as typeof import("../../app/api/executive/history/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/history/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/history/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/executive/history/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/executive/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/executive/overview">> = Specific
  const handler = {} as typeof import("../../app/api/executive/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/finance/reports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/reports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/finance/reports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/finance/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/reports">> = Specific
  const handler = {} as typeof import("../../app/api/finance/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/finance/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance/upload">> = Specific
  const handler = {} as typeof import("../../app/api/finance/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/catalog/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/catalog/add">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/catalog/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/catalog/import-csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/catalog/import-csv">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/catalog/import-csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/catalog/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/catalog/list">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/catalog/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/session/[sessionId]/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/session/[sessionId]/state">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/session/[sessionId]/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/session/commit-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/session/commit-events">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/session/commit-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/session/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/session/create">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/session/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/session/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/session/finalize">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/session/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/upload/start-oauth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/upload/start-oauth">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/upload/start-oauth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/upload/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/upload/submit">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/upload/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/meeting-attendance-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meeting-attendance-proxy">> = Specific
  const handler = {} as typeof import("../../app/api/meeting-attendance-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/schedule-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/schedule-proxy">> = Specific
  const handler = {} as typeof import("../../app/api/schedule-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/supabase-proxy/[...supabasePath]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supabase-proxy/[...supabasePath]">> = Specific
  const handler = {} as typeof import("../../app/api/supabase-proxy/[...supabasePath]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
